modLoader="neoforge"
loaderVersion="[6,)" # NeoForge 6.x support for Minecraft 1.21.1
license="MIT"

[[mods]]
modId="deathalertmod"
version="1.0"
displayName="Death Alert Mod"
description='''
A simple NeoForge mod that detects when a player dies and logs an alert for external tools.
'''

# Optional metadata for your mod
authors="Your Name"
# Here you can also specify dependencies if you have any (for example, another mod or library)

[[dependencies]]
    modId="minecraft"
    version="[1.21.1,1.21.1]"  # Minecraft 1.21.1 version range
    mandatory=true

[[dependencies]]
    modId="neoforge"
    version="[6,)"  # NeoForge version range to ensure compatibility
    mandatory=true
